# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e73070b7e4d193461f1fb87645a2224452fa9109133025e801812550c0d93b1d22ccadee191508e90486736db86d3b9bd1cb642296b048eabdf62eef2016ce7c

test:
  secret_key_base: 4285df77a54d2cea22d2cc78f53cdd3243bcfe7134700fe2d27340c4d463966e880ccd9aeb37e080425185ad6d8f482de74b3821af8e6f4ad088ad8e34384617

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
